/* ============================================================
                JOBFIT-SCORE
Joao Gabriel Boaventura Marques e Silva | RM554874 | 2TDSB-2025
Leo Mota Lima                           | RM557851 | 2TDSB-2025
Lucas Leal das Chagas                   | RM551124 | 2TDSB-2025
============================================================ */
SET SERVEROUTPUT ON;
SET VERIFY OFF;


DROP TABLE vaga_habilidade CASCADE CONSTRAINTS;
DROP TABLE usuario_habilidade CASCADE CONSTRAINTS;
DROP TABLE candidaturas CASCADE CONSTRAINTS;
DROP TABLE cursos CASCADE CONSTRAINTS;
DROP TABLE habilidades CASCADE CONSTRAINTS;
DROP TABLE vagas CASCADE CONSTRAINTS;
DROP TABLE empresas CASCADE CONSTRAINTS;
DROP TABLE usuarios CASCADE CONSTRAINTS;


CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    senha VARCHAR2(200) NOT NULL,
    refresh_token VARCHAR2(200),
    expira_refresh_token DATE,
    criado_em DATE DEFAULT sysdate,
    atualizado_em DATE
);


CREATE TABLE empresas (
    id_empresa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL UNIQUE,
    cnpj VARCHAR2(14) NOT NULL UNIQUE,
    criado_em DATE DEFAULT sysdate
);


CREATE TABLE vagas (
    id_vaga NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    empresa_id NUMBER NOT NULL,
    criado_em DATE DEFAULT sysdate,
    atualizado_em DATE,
    FOREIGN KEY (empresa_id) REFERENCES empresas(id_empresa)
);


CREATE TABLE habilidades (
    id_habilidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL UNIQUE,
    criado_em DATE DEFAULT sysdate
);


CREATE TABLE usuario_habilidade (
    id_usuario_habilidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    habilidade_id NUMBER NOT NULL,
    criado_em DATE DEFAULT sysdate,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (habilidade_id) REFERENCES habilidades(id_habilidade) ON DELETE CASCADE,
    CONSTRAINT unq_usuario_habilidade UNIQUE (usuario_id, habilidade_id)
);


CREATE TABLE cursos (
    id_curso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150) NOT NULL,
    instituicao VARCHAR2(150),
    carga_horaria NUMBER,
    usuario_id NUMBER NOT NULL,
    criado_em DATE DEFAULT sysdate,
    atualizado_em DATE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);


CREATE TABLE candidaturas (
    id_candidatura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    vaga_id NUMBER NOT NULL,
    data_candidatura DATE DEFAULT sysdate,
    status VARCHAR2(50) DEFAULT 'Em Análise',
    criado_em DATE DEFAULT sysdate,
    atualizado_em DATE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (vaga_id) REFERENCES vagas(id_vaga) ON DELETE CASCADE,
    CONSTRAINT chk_status CHECK (status IN ('Em Análise', 'Triagem', 'Aprovado', 'Reprovado'))
);


CREATE TABLE vaga_habilidade (
    id_vaga_habilidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaga_id NUMBER NOT NULL,
    habilidade_id NUMBER NOT NULL,
    criado_em DATE DEFAULT sysdate,
    FOREIGN KEY (vaga_id) REFERENCES vagas(id_vaga) ON DELETE CASCADE,
    FOREIGN KEY (habilidade_id) REFERENCES habilidades(id_habilidade) ON DELETE CASCADE,
    CONSTRAINT unq_vaga_habilidade UNIQUE (vaga_id, habilidade_id)
);


---------

-- Procedure para inserir usuário
CREATE OR REPLACE PROCEDURE sp_inserir_usuario (
    p_nome IN VARCHAR2,
    p_email IN VARCHAR2,
    p_senha IN VARCHAR2,
    p_id_usuario OUT NUMBER
) AS
BEGIN
    INSERT INTO usuarios (nome, email, senha)
    VALUES (p_nome, p_email, p_senha)
    RETURNING id_usuario INTO p_id_usuario;
    
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Email já cadastrado');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Procedure para inserir empresa
CREATE OR REPLACE PROCEDURE sp_inserir_empresa (
    p_nome IN VARCHAR2,
    p_cnpj IN VARCHAR2,
    p_id_empresa OUT NUMBER
) AS
BEGIN
    INSERT INTO empresas (nome, cnpj)
    VALUES (p_nome, p_cnpj)
    RETURNING id_empresa INTO p_id_empresa;
    
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20002, 'Nome ou CNPJ já cadastrado');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Procedure para inserir vaga
CREATE OR REPLACE PROCEDURE sp_inserir_vaga (
    p_titulo IN VARCHAR2,
    p_empresa_id IN NUMBER,
    p_id_vaga OUT NUMBER
) AS
BEGIN
    INSERT INTO vagas (titulo, empresa_id)
    VALUES (p_titulo, p_empresa_id)
    RETURNING id_vaga INTO p_id_vaga;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Procedure para inserir habilidade
CREATE OR REPLACE PROCEDURE sp_inserir_habilidade (
    p_nome IN VARCHAR2,
    p_id_habilidade OUT NUMBER
) AS
BEGIN
    INSERT INTO habilidades (nome)
    VALUES (p_nome)
    RETURNING id_habilidade INTO p_id_habilidade;
    
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20003, 'Habilidade já cadastrada');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Procedure para associar habilidade ao usuário
CREATE OR REPLACE PROCEDURE sp_inserir_usuario_habilidade (
    p_usuario_id IN NUMBER,
    p_habilidade_id IN NUMBER
) AS
BEGIN
    INSERT INTO usuario_habilidade (usuario_id, habilidade_id)
    VALUES (p_usuario_id, p_habilidade_id);
    
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20004, 'Usuário já possui esta habilidade');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Procedure para inserir curso
CREATE OR REPLACE PROCEDURE sp_inserir_curso (
    p_nome IN VARCHAR2,
    p_instituicao IN VARCHAR2,
    p_carga_horaria IN NUMBER,
    p_usuario_id IN NUMBER,
    p_id_curso OUT NUMBER
) AS
BEGIN
    INSERT INTO cursos (nome, instituicao, carga_horaria, usuario_id)
    VALUES (p_nome, p_instituicao, p_carga_horaria, p_usuario_id)
    RETURNING id_curso INTO p_id_curso;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Procedure para inserir candidatura
CREATE OR REPLACE PROCEDURE sp_inserir_candidatura (
    p_usuario_id IN NUMBER,
    p_vaga_id IN NUMBER,
    p_id_candidatura OUT NUMBER
) AS
BEGIN
    INSERT INTO candidaturas (usuario_id, vaga_id)
    VALUES (p_usuario_id, p_vaga_id)
    RETURNING id_candidatura INTO p_id_candidatura;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Procedure para associar habilidade à vaga
CREATE OR REPLACE PROCEDURE sp_inserir_vaga_habilidade (
    p_vaga_id IN NUMBER,
    p_habilidade_id IN NUMBER
) AS
BEGIN
    INSERT INTO vaga_habilidade (vaga_id, habilidade_id)
    VALUES (p_vaga_id, p_habilidade_id);
    
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20005, 'Vaga já possui esta habilidade');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/


-----

DECLARE
    v_id NUMBER;
BEGIN
    sp_inserir_usuario('Ana Paula Santos', 'ana.santos@email.com', 'senha123', v_id);
    sp_inserir_usuario('Carlos Eduardo Lima', 'carlos.lima@email.com', 'senha123', v_id);
    sp_inserir_usuario('Mariana Costa Silva', 'mariana.costa@email.com', 'senha123', v_id);
    sp_inserir_usuario('Ricardo Almeida', 'ricardo.almeida@email.com', 'senha123', v_id);
    sp_inserir_usuario('Juliana Ferreira', 'juliana.ferreira@email.com', 'senha123', v_id);
    sp_inserir_usuario('Fernando Oliveira', 'fernando.oliveira@email.com', 'senha123', v_id);
    sp_inserir_usuario('Beatriz Rodrigues', 'beatriz.rodrigues@email.com', 'senha123', v_id);
    sp_inserir_usuario('Paulo Henrique Souza', 'paulo.souza@email.com', 'senha123', v_id);
    sp_inserir_usuario('Camila Martins', 'camila.martins@email.com', 'senha123', v_id);
    sp_inserir_usuario('Gabriel Pereira', 'gabriel.pereira@email.com', 'senha123', v_id);
    DBMS_OUTPUT.PUT_LINE('10 usuários inseridos com sucesso!');
END;
/


DECLARE
    v_id NUMBER;
BEGIN
    sp_inserir_empresa('Tech Solutions Brasil', '12345678000190', v_id);
    sp_inserir_empresa('Inovação Digital Ltda', '98765432000145', v_id);
    sp_inserir_empresa('Consultoria TI Express', '11223344000156', v_id);
    sp_inserir_empresa('Desenvolve Software SA', '55667788000198', v_id);
    sp_inserir_empresa('Cloud Computing Brasil', '99887766000132', v_id);
    sp_inserir_empresa('Data Science Corp', '44556677000178', v_id);
    sp_inserir_empresa('Agile Developers', '33221100000165', v_id);
    sp_inserir_empresa('Web Solutions Pro', '77889900000123', v_id);
    sp_inserir_empresa('Mobile Apps Brasil', '66554433000187', v_id);
    sp_inserir_empresa('Cyber Security Tech', '22334455000141', v_id);
    DBMS_OUTPUT.PUT_LINE('10 empresas inseridas com sucesso!');
END;
/


DECLARE
    v_id NUMBER;
BEGIN
    sp_inserir_habilidade('Java', v_id);
    sp_inserir_habilidade('Python', v_id);
    sp_inserir_habilidade('JavaScript', v_id);
    sp_inserir_habilidade('SQL', v_id);
    sp_inserir_habilidade('React', v_id);
    sp_inserir_habilidade('Node.js', v_id);
    sp_inserir_habilidade('Docker', v_id);
    sp_inserir_habilidade('Kubernetes', v_id);
    sp_inserir_habilidade('AWS', v_id);
    sp_inserir_habilidade('Git', v_id);
    DBMS_OUTPUT.PUT_LINE('10 habilidades inseridas com sucesso!');
END;
/


DECLARE
    v_id NUMBER;
BEGIN
    sp_inserir_vaga('Desenvolvedor Java Pleno', 1, v_id);
    sp_inserir_vaga('Analista Python Sênior', 2, v_id);
    sp_inserir_vaga('Desenvolvedor Full Stack', 3, v_id);
    sp_inserir_vaga('Engenheiro de Dados', 4, v_id);
    sp_inserir_vaga('Arquiteto de Soluções Cloud', 5, v_id);
    sp_inserir_vaga('Cientista de Dados', 6, v_id);
    sp_inserir_vaga('Scrum Master', 7, v_id);
    sp_inserir_vaga('Desenvolvedor Front-End React', 8, v_id);
    sp_inserir_vaga('Desenvolvedor Mobile Android', 9, v_id);
    sp_inserir_vaga('Analista de Segurança da Informação', 10, v_id);
    sp_inserir_vaga('DevOps Engineer', 1, v_id);
    sp_inserir_vaga('Desenvolvedor Back-End Node.js', 2, v_id);
    sp_inserir_vaga('Tech Lead Java', 3, v_id);
    sp_inserir_vaga('Engenheiro de Software', 4, v_id);
    sp_inserir_vaga('Analista de Banco de Dados', 5, v_id);
    DBMS_OUTPUT.PUT_LINE('15 vagas inseridas com sucesso!');
END;
/


BEGIN
    -- Ana Paula (usuário 1) - Java, SQL, Git
    sp_inserir_usuario_habilidade(1, 1);
    sp_inserir_usuario_habilidade(1, 4);
    sp_inserir_usuario_habilidade(1, 10);
    
    -- Carlos Eduardo (usuário 2) - Python, SQL, AWS
    sp_inserir_usuario_habilidade(2, 2);
    sp_inserir_usuario_habilidade(2, 4);
    sp_inserir_usuario_habilidade(2, 9);
    
    -- Mariana Costa (usuário 3) - JavaScript, React, Node.js
    sp_inserir_usuario_habilidade(3, 3);
    sp_inserir_usuario_habilidade(3, 5);
    sp_inserir_usuario_habilidade(3, 6);
    
    -- Ricardo Almeida (usuário 4) - Python, SQL, Docker
    sp_inserir_usuario_habilidade(4, 2);
    sp_inserir_usuario_habilidade(4, 4);
    sp_inserir_usuario_habilidade(4, 7);
    
    -- Juliana Ferreira (usuário 5) - AWS, Docker, Kubernetes
    sp_inserir_usuario_habilidade(5, 9);
    sp_inserir_usuario_habilidade(5, 7);
    sp_inserir_usuario_habilidade(5, 8);
    
    -- Fernando Oliveira (usuário 6) - Java, Docker, Git
    sp_inserir_usuario_habilidade(6, 1);
    sp_inserir_usuario_habilidade(6, 7);
    sp_inserir_usuario_habilidade(6, 10);
    
    -- Beatriz Rodrigues (usuário 7) - JavaScript, React, Git
    sp_inserir_usuario_habilidade(7, 3);
    sp_inserir_usuario_habilidade(7, 5);
    sp_inserir_usuario_habilidade(7, 10);
    
    -- Paulo Henrique (usuário 8) - Node.js, JavaScript, Docker
    sp_inserir_usuario_habilidade(8, 6);
    sp_inserir_usuario_habilidade(8, 3);
    sp_inserir_usuario_habilidade(8, 7);
    
    -- Camila Martins (usuário 9) - Java, SQL, AWS
    sp_inserir_usuario_habilidade(9, 1);
    sp_inserir_usuario_habilidade(9, 4);
    sp_inserir_usuario_habilidade(9, 9);
    
    -- Gabriel Pereira (usuário 10) - Python, Kubernetes, AWS
    sp_inserir_usuario_habilidade(10, 2);
    sp_inserir_usuario_habilidade(10, 8);
    sp_inserir_usuario_habilidade(10, 9);
    
    DBMS_OUTPUT.PUT_LINE('Habilidades dos usuários inseridas com sucesso!');
END;
/


DECLARE
    v_id NUMBER;
BEGIN
    sp_inserir_curso('Java Avançado', 'Alura', 40, 1, v_id);
    sp_inserir_curso('Python para Data Science', 'Coursera', 60, 2, v_id);
    sp_inserir_curso('React do Zero ao Avançado', 'Udemy', 50, 3, v_id);
    sp_inserir_curso('Banco de Dados Oracle', 'FIAP', 80, 4, v_id);
    sp_inserir_curso('AWS Solutions Architect', 'AWS Training', 120, 5, v_id);
    sp_inserir_curso('Docker e Kubernetes', 'LinuxTips', 40, 6, v_id);
    sp_inserir_curso('JavaScript Moderno', 'Rocketseat', 35, 7, v_id);
    sp_inserir_curso('Node.js Completo', 'Udemy', 45, 8, v_id);
    sp_inserir_curso('Scrum Master Certification', 'Scrum.org', 16, 9, v_id);
    sp_inserir_curso('Segurança da Informação', 'Descomplica', 60, 10, v_id);
    sp_inserir_curso('Git e GitHub', 'Digital Innovation One', 20, 1, v_id);
    sp_inserir_curso('Machine Learning', 'Coursera', 80, 2, v_id);
    DBMS_OUTPUT.PUT_LINE('Cursos inseridos com sucesso!');
END;
/


BEGIN
    -- Vaga 1: Desenvolvedor Java Pleno
    sp_inserir_vaga_habilidade(1, 1); -- Java
    sp_inserir_vaga_habilidade(1, 4); -- SQL
    sp_inserir_vaga_habilidade(1, 10); -- Git
    
    -- Vaga 2: Analista Python Sênior
    sp_inserir_vaga_habilidade(2, 2); -- Python
    sp_inserir_vaga_habilidade(2, 4); -- SQL
    
    -- Vaga 3: Desenvolvedor Full Stack
    sp_inserir_vaga_habilidade(3, 3); -- JavaScript
    sp_inserir_vaga_habilidade(3, 5); -- React
    sp_inserir_vaga_habilidade(3, 6); -- Node.js
    
    -- Vaga 4: Engenheiro de Dados
    sp_inserir_vaga_habilidade(4, 2); -- Python
    sp_inserir_vaga_habilidade(4, 4); -- SQL
    sp_inserir_vaga_habilidade(4, 7); -- Docker
    
    -- Vaga 5: Arquiteto de Soluções Cloud
    sp_inserir_vaga_habilidade(5, 9); -- AWS
    sp_inserir_vaga_habilidade(5, 7); -- Docker
    sp_inserir_vaga_habilidade(5, 8); -- Kubernetes
    
    -- Vaga 6: Cientista de Dados
    sp_inserir_vaga_habilidade(6, 2); -- Python
    sp_inserir_vaga_habilidade(6, 4); -- SQL
    
    -- Vaga 7: Scrum Master
    sp_inserir_vaga_habilidade(7, 10); -- Git
    
    -- Vaga 8: Desenvolvedor Front-End React
    sp_inserir_vaga_habilidade(8, 3); -- JavaScript
    sp_inserir_vaga_habilidade(8, 5); -- React
    
    -- Vaga 9: Desenvolvedor Mobile Android
    sp_inserir_vaga_habilidade(9, 1); -- Java
    sp_inserir_vaga_habilidade(9, 10); -- Git
    
    -- Vaga 10: Analista de Segurança
    sp_inserir_vaga_habilidade(10, 2); -- Python
    sp_inserir_vaga_habilidade(10, 4); -- SQL
    
    -- Vaga 11: DevOps Engineer
    sp_inserir_vaga_habilidade(11, 7); -- Docker
    sp_inserir_vaga_habilidade(11, 8); -- Kubernetes
    sp_inserir_vaga_habilidade(11, 9); -- AWS
    
    -- Vaga 12: Desenvolvedor Back-End Node.js
    sp_inserir_vaga_habilidade(12, 6); -- Node.js
    sp_inserir_vaga_habilidade(12, 4); -- SQL
    
    DBMS_OUTPUT.PUT_LINE('Habilidades das vagas inseridas com sucesso!');
END;
/


DECLARE
    v_id NUMBER;
BEGIN
    -- Ana Paula se candidata às vagas de Java
    sp_inserir_candidatura(1, 1, v_id);
    sp_inserir_candidatura(1, 9, v_id);
    
    -- Carlos Eduardo se candidata às vagas de Python
    sp_inserir_candidatura(2, 2, v_id);
    sp_inserir_candidatura(2, 4, v_id);
    sp_inserir_candidatura(2, 6, v_id);
    
    -- Mariana Costa se candidata às vagas de Front-End
    sp_inserir_candidatura(3, 3, v_id);
    sp_inserir_candidatura(3, 8, v_id);
    
    -- Ricardo Almeida se candidata às vagas de Dados
    sp_inserir_candidatura(4, 4, v_id);
    sp_inserir_candidatura(4, 6, v_id);
    
    -- Juliana Ferreira se candidata às vagas de Cloud
    sp_inserir_candidatura(5, 5, v_id);
    sp_inserir_candidatura(5, 11, v_id);
    
    -- Fernando Oliveira se candidata às vagas de Java
    sp_inserir_candidatura(6, 1, v_id);
    sp_inserir_candidatura(6, 13, v_id);
    
    -- Beatriz Rodrigues se candidata às vagas de Front-End
    sp_inserir_candidatura(7, 8, v_id);
    sp_inserir_candidatura(7, 3, v_id);
    
    -- Paulo Henrique se candidata às vagas de Node.js
    sp_inserir_candidatura(8, 12, v_id);
    sp_inserir_candidatura(8, 3, v_id);
    
    -- Camila Martins se candidata às vagas de Java
    sp_inserir_candidatura(9, 1, v_id);
    
    -- Gabriel Pereira se candidata às vagas de Cloud
    sp_inserir_candidatura(10, 5, v_id);
    sp_inserir_candidatura(10, 11, v_id);
    
    DBMS_OUTPUT.PUT_LINE('Candidaturas inseridas com sucesso!');
END;
/