-- ==============================
-- JOBFIT SCORE - MODELO 3FN
-- BANCO RELACIONAL (ORACLE)
-- ==============================
DROP TABLE vaga_habilidade CASCADE CONSTRAINTS;
DROP TABLE usuario_habilidade CASCADE CONSTRAINTS;
DROP TABLE candidaturas CASCADE CONSTRAINTS;
DROP TABLE cursos CASCADE CONSTRAINTS;
DROP TABLE habilidades CASCADE CONSTRAINTS;
DROP TABLE vagas CASCADE CONSTRAINTS;
DROP TABLE empresas CASCADE CONSTRAINTS;
DROP TABLE usuarios CASCADE CONSTRAINTS;



CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    senha VARCHAR2(200) NOT NULL,
    refresh_token VARCHAR2(200),
    expira_refresh_token DATE,
    criado_em DATE DEFAULT sysdate,
    atualizado_em DATE
);

CREATE TABLE empresas (
    id_empresa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL UNIQUE,
    cnpj VARCHAR2(14) NOT NULL UNIQUE,
    criado_em DATE DEFAULT sysdate
);

CREATE TABLE vagas (
    id_vaga NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    empresa_id NUMBER NOT NULL,
    criado_em DATE DEFAULT sysdate,
    atualizado_em DATE,
    FOREIGN KEY (empresa_id) REFERENCES empresas(id_empresa)
);


CREATE TABLE habilidades (
    id_habilidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL UNIQUE,
    criado_em DATE DEFAULT sysdate
);

CREATE TABLE usuario_habilidade (
    id_usuario_habilidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    habilidade_id NUMBER NOT NULL,
    criado_em DATE DEFAULT sysdate,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (habilidade_id) REFERENCES habilidades(id_habilidade) ON DELETE CASCADE,
    CONSTRAINT unq_usuario_habilidade UNIQUE (usuario_id, habilidade_id)
);

CREATE TABLE cursos (
    id_curso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150) NOT NULL,
    instituicao VARCHAR2(150),
    carga_horaria NUMBER,
    usuario_id NUMBER NOT NULL,
    criado_em DATE DEFAULT sysdate,
    atualizado_em DATE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);


CREATE TABLE candidaturas (
    id_candidatura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    vaga_id NUMBER NOT NULL,
    data_candidatura DATE DEFAULT sysdate,
    status VARCHAR2(50) DEFAULT 'Em Análise',
    criado_em DATE DEFAULT sysdate,
    atualizado_em DATE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (vaga_id) REFERENCES vagas(id_vaga) ON DELETE CASCADE,
    CONSTRAINT chk_status CHECK (status IN ('Em Análise', 'Triagem', 'Aprovado', 'Reprovado'))
);


CREATE TABLE vaga_habilidade (
    id_vaga_habilidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaga_id NUMBER NOT NULL,
    habilidade_id NUMBER NOT NULL,
    criado_em DATE DEFAULT sysdate,
    FOREIGN KEY (vaga_id) REFERENCES vagas(id_vaga) ON DELETE CASCADE,
    FOREIGN KEY (habilidade_id) REFERENCES habilidades(id_habilidade) ON DELETE CASCADE,
    CONSTRAINT unq_vaga_habilidade UNIQUE (vaga_id, habilidade_id)
);
